app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: '/{_locale}'
    defaults:
        _locale: en
    requirements:
        _locale: '[a-z]{2}'

root:
    path: /
    methods: GET
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage

logout:
    path: /logout
    methods: GET
