app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: '/{_locale}'
    defaults:
        _locale: en
    requirements:
        _locale: '[a-z]{2}'

logout:
    path: /logout
    methods: GET
