# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    app.dictionaries:
        - '%kernel.project_dir%/app/Resources/data/test.txt'
        - '%kernel.project_dir%/app/Resources/data/words.txt'
        - '%kernel.project_dir%/app/Resources/data/words.xml'

services:
    _defaults:
        public: false
        autowire: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Contact\ContactMailer:
        public: true
        arguments:
            $sendTo: '%app.contact.send_to%'

    AppBundle\Game\WordList:
        calls:
            - method: addLoader
              arguments: [txt, '@AppBundle\Game\Loader\TextFileLoader']
            - method: addLoader
              arguments: [xml, '@AppBundle\Game\Loader\XmlFileLoader']
            - method: loadDictionaries
              arguments:
                   - '%app.dictionaries%'

    AppBundle\Game\GameRunner:
        public: true
